// Module included in the following assemblies:
//
// * operating/manage-cluster-configuration.adoc
:_module-type: CONCEPT
[id="configuration-management-view_{context}"]
= Configuration management view

[role="_abstract"]
To open the *Configuration Management* view, select *Configuration Management* from the left-hand navigation menu.
Similar to the *Dashboard*, it displays some useful widgets.

[discrete]
== Widgets
The *Configuration Management* view includes multiple interactive widgets to show information about:

* Policy violations by severity.
* The state of CIS (Center for Information Security) Docker and Kubernetes  benchmark controls.
* Users with administrator rights in the most clusters.
* Secrets used most widely in your clusters.

[discrete]
== Header
The *Configuration Management* view header shows you the number of policies and CIS controls and allows you to switch between different entities.
For example, you can:

* Click *Policies* to view all policies and their severity, or select *CIS Controls* to view detailed information about all controls.
* Click *Application and Infrastructure* and then you can select clusters, namespaces, nodes, deployments, images, and secrets to view detailed information about them.
* Click *RBAC Visibility and Configuration* and then you can select users and groups, service accounts, and roles to view detailed information about them.
