// Module included in the following assemblies:
//
// * operating/use-admission-controller-enforcement.adoc
:_module-type: PROCEDURE
[id="disable-associated-policies_{context}"]
= Disabling associated policies

[role="_abstract"]
You can turn off the enforcement on relevant policies, which in turn instructs the admission controller to skip enforcements.

.Procedure
. On the RHACS portal, navigate to *Platform Configuration* -> *System Policies*.
. Disable enforcement on the default policies:
** In the policies view, scroll down and move your mouse over to the *Kubernetes Actions: Exec into Pod* policy.
Then select the power icon to disable the policy.
** In the policies view, scroll down and move your mouse over to the *Kubernetes Actions: Port Forward to Pod* policy.
Then select the power icon to disable the policy.
. Disable enforcement on any other custom policies that you have created by using criteria from the default *Kubernetes Actions: Port Forward to Pod* and *Kubernetes Actions: Exec into Pod* policies.
