// Module included in the following assemblies:
//
// * operating/manage-cluster-configuration.adoc
:_module-type: PROCEDURE
[id="service-accounts-permissions_{context}"]
= Finding service accounts and their permissions

[role="_abstract"]
Use the *Configuration Management* view to find out where service accounts are in use and their permissions.

.Procedure
. Navigate to the RHACS portal and click *Configuration Management* from the left-hand navigation menu.
. Select *RBAC Visibility and Configuration* -> *Service Accounts* from the *Configuration Management* view header.
The *Service Accounts* view displays a list of Kubernetes service accounts across your clusters, their assigned roles, whether the `cluster-admin` role is enabled, and which deployments use them.
. Select a row (or one of the underlined links in a row) to view more details, including which cluster and namespace permissions are granted to the selected service account.
The information appears in a panel on the right.
