// Module included in the following assemblies:
//
// * operating/manage-network-policies.adoc
:_module-type: PROCEDURE
[id="simulate-network-policies_{context}"]
= Simulating network policies

[role="_abstract"]
Your current network policies may allow unneeded network communications.
To simulate the effects of a new set of network policies, use the network policy simulator.

.Procedure
. On the RHACS portal, select *Network Graph* from the left-hand navigation menu.
. On the *Network Graph* view header, select *Network Policy Simulator*.
. Select *Upload and simulate network policy YAML* and upload your proposed YAML file.
The network graph view displays what your proposed network policies would achieve.
. To share your proposed policies with your team, select *Share YAML*.
To apply your policy directly, select *Apply Network Policies*.

[WARNING]
====
Applying network policies directly can cause problems for running applications.
Be sure to test policies in development or testing clusters before applying them to production workloads.
====
