// Module included in the following assemblies:
//
// * operating/manage-security-policies.adoc
:_module-type: CONCEPT
[id="use-out-of-box-security-policies_{context}"]
= Using out-of-box security policies

[role="_abstract"]
{product-title} includes a set of default policies that provide broad coverage to identify security issues and ensure best practices for security in your environment.

To view the default policies:

* On the RHACS portal, navigate to *Platform Configuration* -> *System policies*.

The Policies view lists the default policies and includes the following parameters for each policy:

* *Name*: A short name for the policy.
* *Description*: A longer, more detailed description of the alert for the policy.
* *Lifecycle*: Corresponds to which phase of the container lifecycle, build, deploy, or runtime, does this policy applies, and the phase at which enforcement will be applied, when the policy is enabled.
* *Severity*: A ranking of the policy, either Critical, High, Medium, or Low, for the amount of attention required.

The default policies have pre-configured parameters and belong to categories such as:

* Anomalous Activity
* Cryptocurrency Mining
* DevOps Best Practices
* Kubernetes
* Network Tools
* Package Management
* Privileges
* Security Best Practices
* System Modification
* Vulnerability Management

You can edit these categories create your own categories.
//Add link create your own categories
When you create your own category, a new widget displays information about that category on the Dashboard.
