[id="manage-cluster-configuration"]
= Managing cluster configuration
include::modules/common-attributes.adoc[]
:context: manage-cluster-configuration

toc::[]

[role="_abstract"]
Learn how to use the Configuration Management view and understand the correlation between various entities in your cluster to manage your cluster configuration efficiently.

Every Kubernetes or {ocp} cluster includes many different entities distributed throughout the cluster, which makes it more challenging to understand and act on the available information.

{product-title} provides efficient configuration management that combines all these distributed entities on a single page.
It brings together information about all your clusters, namespaces, nodes, deployments, images, secrets, users, groups, service accounts, and roles in a single *Configuration Management* view, helping you visualize different entities and the connections between them.

include::modules/configuration-management-view.adoc[leveloffset=+1]

[id="misconfigurations-kubernetes-rbac"]
== Identifying misconfigurations in Kubernetes roles

Use the *Configuration Management* view to identify potential misconfigurations, such as users, groups, or service accounts granted the `cluster-admin` role, or find roles that are not granted to anyone.

include::modules/kubernetes-role-assignment.adoc[leveloffset=+2]

include::modules/service-accounts-permissions.adoc[leveloffset=+2]

include::modules/unused-kubernetes-roles.adoc[leveloffset=+2]

include::modules/view-kubernetes-secrets.adoc[leveloffset=+1]

include::modules/find-policy-violations.adoc[leveloffset=+1]


[id="using-comments-and-tags"]
== Using comments and tags

You can use tags and comments to specify what is happening with violations to keep your team up to date.
Comments allow you to add text notes to violations and tags allow you to categorize your violations.

:smallporv: violation
:smallpluralporv: violations
:capsporv: Violation
:capspluralporv: Violations

include::modules/adding-comments.adoc[leveloffset=+2]

include::modules/adding-tags.adoc[leveloffset=+2]

include::modules/find-failing-cis-controls.adoc[leveloffset=+1]
